### ISSUE TITLE
How can i expand it touch / Clicking 

### ISSUE THREAD

**Issue by Qalbarq** [SouthernBox/ParallaxRecyclerView#3]
Hello 
Thanks for your research on parallax recyclerView and the code is working very fine, I am trying used this to show My Booking History Page, actual the problem i am facing is am not able to show details History of Booking after click in the same page. If you can suggest me the best it would be great of you .

and i am attach an image i want look like this .
![parallaxrecyclerview](https://user-images.githubusercontent.com/43772174/46330971-4a7ae580-c633-11e8-8ee7-ccbdb2694b4d.gif)

Thanks Again

**Comment by Qalbarq** [comment]
Give me better suggest for me.
thanks

**Comment by NanBox** [comment]
You can put the expansion in item layout, than control the display and hiding of the expansion.
